import { type ReactNode } from "react";
import Head from 'next/head';
import { Provider } from "react-redux";
import store from "@/store/store";
import NavMain from "./NavMain";

interface Props {
  children?: ReactNode
  title?: string
}

const LayoutMain = ({ children, title }: Props) => {
  return (
    <Provider store={store}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#ffffff" />
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <title>{title}</title>
      </Head>

      <NavMain />

      {children}
    </Provider>
  );
};
  
export default LayoutMain;
